const RuntimeStatus = {

    SUCCESS: "SUCCESS",

    RECOGNITION_FAILED: "RECOGNITION_FAILED",

    DEFINITION_FAILED: "DEFINITION_FAILED",

    EVIDENCE_MISSING: "EVIDENCE_MISSING",

    CORRESPONDENCE_FAILED: "CORRESPONDENCE_FAILED",

    REASONING_FAILED: "REASONING_FAILED",

    RESPONSIBILITY_FAILED: "RESPONSIBILITY_FAILED",

    RECONSTRUCTION_FAILED: "RECONSTRUCTION_FAILED"

};

export default RuntimeStatus;
